### ISSUE TITLE
Gitbook landing page blank

### ISSUE THREAD

**Issue by BenRussert** [Hugoberry/PowerQuery#2]
Hi, thanks for this extremely helpful repo and site.

I noticed the landing page is blank when you go to the main site [`https://www.powerquery.io/`](https://www.powerquery.io/). 

![image](https://user-images.githubusercontent.com/10860657/46698103-7a962b80-cbd3-11e8-9886-cfaf88e88a62.png)

The page I was looking for is now at: [`https://www.powerquery.io/v/published/`](https://www.powerquery.io/v/published/)

**Comment by Hugoberry** [comment]
Was sliently migrating this to the latest version of Gitbook which kind of broke a couple of things. I've fixed that.
https://www.powerquery.io/ should work as expected
